export const menuItems = [
  { name: "Grilled Chicken Breast", price: 8.99, category: "Main Courses" },
  { name: "Vegetarian Pasta", price: 7.49, category: "Main Courses" },
  { name: "Beef Burger", price: 9.99, category: "Main Courses" },
  { name: "French Fries", price: 3.49, category: "Sides" },
  { name: "Garden Salad", price: 4.99, category: "Sides" },
  { name: "Mashed Potatoes", price: 3.99, category: "Sides" },
  { name: "Orange Juice", price: 2.99, category: "Beverages" },
  { name: "Apple Juice", price: 2.99, category: "Beverages" },
  { name: "Bottled Water", price: 1.49, category: "Beverages" },
  { name: "Chocolate Brownie", price: 3.49, category: "Desserts" },
  { name: "Fruit Salad", price: 4.29, category: "Desserts" },
  { name: "Yogurt Parfait", price: 4.99, category: "Snacks" },
  { name: "Cheese Stick", price: 1.99, category: "Snacks" },
];
