export const menuItems = [
  {
    name: "Смажена куряча грудка",
    description: "Соковита смажена куряча грудка з ароматними спеціями.",
    imageUrl: "/uploads/menu-images/grilled-chicken-breast.jpg",
    price: 8.99,
    category: "Основні страви",
  },
  {
    name: "Вегетаріанська паста",
    description: "Паста з овочами та томатним соусом.",
    imageUrl: "/uploads/menu-images/vegetarian-pasta.jpg",
    price: 7.49,
    category: "Основні страви",
  },
  {
    name: "Бургер з яловичини",
    description: "Соковитий бургер з яловичини з сиром та овочами.",
    imageUrl: "/uploads/menu-images/beef-burger.jpg",
    price: 9.99,
    category: "Основні страви",
  },
  {
    name: "Картопля фрі",
    description: "Хрустка картопля фрі, приправлена сіллю.",
    imageUrl: "/uploads/menu-images/french-fries.jpg",
    price: 3.49,
    category: "Гарніри",
  },
  {
    name: "Салат з овочів",
    description: "Свіжий салат з різноманітних овочів з легким вінегретом.",
    imageUrl: "/uploads/menu-images/garden-salad.jpg",
    price: 4.99,
    category: "Гарніри",
  },
  {
    name: "Картопляне пюре",
    description: "Кремове картопляне пюре з вершковим маслом.",
    imageUrl: "/uploads/menu-images/mashed-potatoes.jpg",
    price: 3.99,
    category: "Гарніри",
  },
  {
    name: "Апельсиновий сік",
    description: "Свіжовижатий апельсиновий сік.",
    imageUrl: "/uploads/menu-images/orange-juice.jpg",
    price: 2.99,
    category: "Напої",
  },
  {
    name: "Яблучний сік",
    description: "Свіжовижатий яблучний сік.",
    imageUrl: "/uploads/menu-images/apple-juice.jpg",
    price: 2.99,
    category: "Напої",
  },
  {
    name: "Мінеральна вода",
    description: "Освіжаюча мінеральна вода.",
    imageUrl: "/uploads/menu-images/bottled-water.jpg",
    price: 1.49,
    category: "Напої",
  },
  {
    name: "Шоколадний брауні",
    description: "Смачний шоколадний брауні з горіхами.",
    imageUrl: "/uploads/menu-images/chocolate-brownie.jpg",
    price: 3.49,
    category: "Десерти",
  },
  {
    name: "Фруктовий салат",
    description: "Свіжий фруктовий салат з сезонних фруктів.",
    imageUrl: "/uploads/menu-images/fruit-salad.jpg",
    price: 4.29,
    category: "Десерти",
  },
  {
    name: "Йогуртовий парфе",
    description: "Йогурт з шарами граноли та свіжих ягід.",
    imageUrl: "/uploads/menu-images/yogurt-parfait.jpg",
    price: 4.99,
    category: "Закуски",
  },
  {
    name: "Сирна паличка",
    description: "Смажена сирна паличка з томатним соусом.",
    imageUrl: "/uploads/menu-images/cheese-stick.jpg",
    price: 1.99,
    category: "Закуски",
  },
];
