export const menuItems = [
  { name: "Смажена куряча грудка", price: 8.99, category: "Основні страви" },
  { name: "Вегетаріанська паста", price: 7.49, category: "Основні страви" },
  { name: "Бургер з яловичини", price: 9.99, category: "Основні страви" },
  { name: "Картопля фрі", price: 3.49, category: "Гарніри" },
  { name: "Салат з овочів", price: 4.99, category: "Гарніри" },
  { name: "Картопляне пюре", price: 3.99, category: "Гарніри" },
  { name: "Апельсиновий сік", price: 2.99, category: "Напої" },
  { name: "Яблучний сік", price: 2.99, category: "Напої" },
  { name: "Бутильована вода", price: 1.49, category: "Напої" },
  { name: "Шоколадний брауні", price: 3.49, category: "Десерти" },
  { name: "Фруктовий салат", price: 4.29, category: "Десерти" },
  { name: "Йогуртовий парфе", price: 4.99, category: "Закуски" },
  { name: "Сирна паличка", price: 1.99, category: "Закуски" },
];
